name: Run Repository Tests
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/959426188245/locations/global/workloadIdentityPools/github-action-pool-1/providers/github-action-provider-1'
          service_account: 'artifact-repository-access@roomr-222721.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
      - name: Checkout MySQL Repo
        uses: actions/checkout@v3
        with:
          repository: sneyd321/mysql-docker-kubernetes
          path: mysql-docker-kubernetes
      - name: Build MySQL
        run: |
          docker build -t sneyd321/mysql ./mysql-docker-kubernetes
      - name: Boot Docker Compose
        run: |
          docker compose up -d
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Alembic
        run: |
          alembic revision --autogenerate
          alembic upgrade head
      - name: Create Firebase Service Account
        run: |
          gcloud iam service-accounts keys create ./models/static/ServiceAccount.json --iam-account=firebase-adminsdk-rbs1y@roomr-222721.iam.gserviceaccount.com
      - name: Test with pytest
        run: |
          pytest tests/test_repository.py --asyncio-mode=strict
      - name: Delete Service Account Key
        run: |
          python ./models/static/remove_key.py
